
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import dotenv from "dotenv";
import path from "path";

// 💡 強制讀取 Next.js 慣用的 .env.local
dotenv.config({ path: path.resolve(process.cwd(), ".env") });
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
       // 這是給一般操作用的
    directUrl: env("DIRECT_URL")      // 這是給同步結構 (push/migrate) 用的
  },
});
